name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Reponu klonlamaq
    - name: Check out repository
      uses: actions/checkout@v2

    # GitHub serverinin host açarını "known_hosts" faylına əlavə etmək
    - name: Add GitHub to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    # SSH agentini qurmaq və private key-i əlavə etmək
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    # SSH bağlantısını test etmək
    - name: Test SSH connection
      run: ssh -vT git@github.com

    # DigitalOcean serverinə deploy etmək
    - name: Deploy to DigitalOcean
      run: |
        ssh root@159.65.222.87 "cd /erkey/project && git pull origin main && ./deploy.sh"
